1 : Importations et téléchargements

In [ ]:
#importation les bibliothéques nécessaires
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

# Téléchargement des packages NLTK nécessaires
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

2 : Chargement des données nettoyées

In [2]:
# Chargement les données
df_enron = pd.read_csv('../data/enron_clean.csv')

# Afficher les premières lignes pour vérifier
df_enron.head()

  Spam/Ham                                         clean_text
0      ham                      christmas tree farm pictures
1      ham  vastar resources , inc . gary , production fro...
2      ham  calpine daily gas nomination - calpine daily g...
3      ham  re : issue fyi - see note below - already done...
4      ham  meter 7268 nov allocation fyi .\n- - - - - - -...

3:La fonction de prétraitement

In [3]:
# Définition des stopwords en anglais
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    """
    Fonction pour prétraiter le texte :
    1. Convertir en minuscules.
    2. Supprimer la ponctuation.
    3. Tokenizer et supprimer les stopwords.
    """
    # Sécurité : s'assurer que l'entrée est bien lue comme du texte
    text = str(text)
    
    text = text.lower()
    text = ''.join([char for char in text if char not in string.punctuation])
    tokens = word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    
    return ' '.join(tokens)

4 : Application du traitement

In [4]:
print("Début du prétraitement du texte...")

# On crée une nouvelle colonne 'text_preprocessed' en appliquant ta fonction
df_enron['text_preprocessed'] = df_enron['clean_text'].apply(preprocess_text)

print("✅ Prétraitement terminé !")
df_enron[['clean_text', 'text_preprocessed']].head() # Comparaison avant/après

Début du prétraitement du texte...
✅ Prétraitement terminé !

,clean_text,text_preprocessed
0,christmas tree farm pictures,christmas tree farm pictures
1,"vastar resources , inc . gary , production fro...",vastar resources inc gary production high isla...
2,calpine daily gas nomination - calpine daily g...,calpine daily gas nomination calpine daily gas...
3,re : issue fyi - see note below - already done...,issue fyi see note already done stella forward...
4,meter 7268 nov allocation fyi .\n- - - - - - -...,meter 7268 nov allocation fyi forwarded lauri ...

5 : Encodage de la cible (Spam/Ham)

In [5]:
 

# Transformer spam en 1 et ham en 0
df_enron['Spam/Ham'] = df_enron['Spam/Ham'].map({'spam': 1, 'ham': 0})
#Afficher 
df_enron.head()

,Spam/Ham,clean_text,text_preprocessed
0,0,christmas tree farm pictures,christmas tree farm pictures
1,0,"vastar resources , inc . gary , production fro...",vastar resources inc gary production high isla...
2,0,calpine daily gas nomination - calpine daily g...,calpine daily gas nomination calpine daily gas...
3,0,re : issue fyi - see note below - already done...,issue fyi see note already done stella forward...
4,0,meter 7268 nov allocation fyi .\n- - - - - - -...,meter 7268 nov allocation fyi forwarded lauri ...

6:Sauvegarder

In [6]:
#Supprimer la colonne "clean_text"
df_enron = df_enron.drop(columns=['clean_text'])
#Afficher
df_enron.head()

   Spam/Ham                                  text_preprocessed
0         0                       christmas tree farm pictures
1         0  vastar resources inc gary production high isla...
2         0  calpine daily gas nomination calpine daily gas...
3         0  issue fyi see note already done stella forward...
4         0  meter 7268 nov allocation fyi forwarded lauri ...

In [7]:
#Sauvegarder le dataset final
chemin_sauvegarde = '../data/enron_preprocessed.csv'
df_enron.to_csv(chemin_sauvegarde, index=False)
print("✅ Colonne 'clean_text' supprimée.")
print(f"✅ Fichier final sauvegardé : {chemin_sauvegarde}")
print(f"Colonnes restantes : {df_enron.columns.tolist()}")
df_enron.head()

✅ Colonne 'clean_text' supprimée.
✅ Fichier final sauvegardé : ../data/enron_preprocessed.csv
Colonnes restantes : ['Spam/Ham', 'text_preprocessed']

   Spam/Ham                                  text_preprocessed
0         0                       christmas tree farm pictures
1         0  vastar resources inc gary production high isla...
2         0  calpine daily gas nomination calpine daily gas...
3         0  issue fyi see note already done stella forward...
4         0  meter 7268 nov allocation fyi forwarded lauri ...